Handle Numpy inputs to Woodwork
alteryx/woodwork pull request #1023
Opened 2021-06-25 23:35 UTC by simha104

- Handle Numpy inputs to Woodwork
- Closes #501

-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request.*

2021-06-28 14:58 UTC, gsheni commented on docs/source/release_notes.rst
> +        * Add handling of numpy inputs to Woodwork (:pr:`1023`)
```suggestion
        * Add support for numpy inputs in ``init_series`` (:pr:`1023`)
```

2021-06-28 16:08 UTC, tamargrey requested changes

2021-06-28 16:08 UTC, tamargrey commented on woodwork/tests/utils/test_accessor_utils.py
> +            assert series.equals(series2)
We should also test that the Woodwork typing information is as expected.

2021-06-28 16:08 UTC, tamargrey commented on woodwork/tests/utils/test_accessor_utils.py
> +            assert series.equals(series2)
Also, as this test grows, it'll probably make sense to separate the multi dimensional array case into its own test. There's not really any shared code between the two tests, so it's better to separate them out so we can potentially see two different bugs at the same time (as opposed to a bug from the first element masking one from the second)

2021-06-28 18:31 UTC, tamargrey commented on woodwork/tests/utils/test_accessor_utils.py
> +    assert series.equals(series2) and series.ww.logical_type == series2.ww.logical_type and series.ww.semantic_tags == series2.ww.semantic_tags
can you make these separate assertions on separate lines? Makes it a little easier to read

2021-06-29 13:25 UTC, tamargrey approved these changes
lgtm!

2021-06-29 15:39 UTC, merged